name: "Test and linter"
on:
  merge_group:
    branches: [ "development" ]
  # push:
  #   branches: [ "development", "development/**" ]
  pull_request:
    branches: [ "development" ]
jobs:
  test:
    name: rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: articles_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Build and run tests
        run: |
          ls -al
          sudo apt -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/rake db:prepare
          bundle exec rspec
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
  #       with:
  #         ruby-version: 3.1.2
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
